security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: Infrastructure\Entity\Doctrine\UserDoctrine
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern: ^/api/login
            security: false
        api_register:
            pattern: ^/api/register
            security: false
        aoi_logout:
            pattern: ^/api/logout
            security: false
        api_is_connected:
            pattern: ^/api/is-connected
            security: false
        main:
            lazy: true
            provider: app_user_provider
            jwt: ~
            custom_authenticator: Infrastructure\Symfony\Security\LoginFormAuthenticator
            entry_point: Infrastructure\Symfony\Security\LoginFormAuthenticator
            logout:
                path: /logout
                csrf_token_manager: security.csrf.token_manager
                csrf_parameter: _csrf_token
                csrf_token_id: logout

    access_control:
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/is-connected, roles: PUBLIC_ACCESS }
        - { path: ^/api/logout, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: FULLY_IDENTIFIED_ACCESS }

lexik_jwt_authentication:
    token_extractors:
        cookie:
            enabled: true
            name: BEARER
