# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Domain\:
        resource: '../src/Domain'
        exclude:
            - '../src/Domain/Entity'
            - '../src/Domain/ViewModel'

    Infrastructure\Symfony\Controller\:
        resource: '../src/Infrastructure/Symfony/Controller'
        tags: ['controller.service_arguments']

    Infrastructure\:
        resource: '../src/Infrastructure'
        exclude:
            - '../src/Infrastructure/Symfony/Controller'
            - '../src/Infrastructure/Twig'

    Infrastructure\Entity\Doctrine\Mapper\NoteMapperDoctrine:
        arguments:
            $participationMapper: '@Infrastructure\Entity\Doctrine\Mapper\ParticipationMapperDoctrine'

    Infrastructure\Entity\Doctrine\Mapper\ParticipationMapperDoctrine:
        arguments:
            $teamMapper: '@Infrastructure\Entity\Doctrine\Mapper\TeamMapperDoctrine'
            $playerMapper: '@Infrastructure\Entity\Doctrine\Mapper\PlayerMapperDoctrine'
            $matchMapper: '@Infrastructure\Entity\Doctrine\Mapper\MatchMapperDoctrine'

    Infrastructure\Entity\Doctrine\Mapper\MatchMapperDoctrine:
        arguments:
            $teamMapper: '@Infrastructure\Entity\Doctrine\Mapper\TeamMapperDoctrine'

    Infrastructure\Entity\Doctrine\Mapper\TeamMapperDoctrine:
        arguments:
            $teamRepository: '@Infrastructure\Repository\Doctrine\TeamRepositoryDoctrine'

    Infrastructure\Entity\Doctrine\Mapper\PlayerMapperDoctrine:
        arguments:
            $teamMapperDoctrine: '@Infrastructure\Entity\Doctrine\Mapper\TeamMapperDoctrine'
            $teamRepository: '@Infrastructure\Repository\Doctrine\TeamRepositoryDoctrine'

    Domain\UseCase\ShowDetailsPlayer\ShowDetailsPlayerUseCase:
        arguments:
            $playerRepository: '@Infrastructure\Repository\Doctrine\PlayerRepositoryDoctrine'
            $participationRepository: '@Infrastructure\Repository\Doctrine\ParticipationRepositoryDoctrine'

    Domain\UseCase\ShowDetailsMatch\ShowDetailsMatchUseCase:
        arguments:
            $matchRepository: '@Infrastructure\Repository\Doctrine\MatchRepositoryDoctrine'
            $participationRepository: '@Infrastructure\Repository\Doctrine\ParticipationRepositoryDoctrine'
            $noteRepository: '@Infrastructure\Repository\Doctrine\NoteRepositoryDoctrine'

    Domain\UseCase\FetchData\FetchDataUseCase:
        arguments:
            $readChampionshipRepository: '@Infrastructure\Repository\Supabase\ChampionshipRepositorySupabase'
            $writeChampionshipRepository: '@Infrastructure\Repository\Doctrine\ChampionshipRepositoryDoctrine'
            $readTeamRepository: '@Infrastructure\Repository\Supabase\TeamRepositorySupabase'
            $writeTeamRepository: '@Infrastructure\Repository\Doctrine\TeamRepositoryDoctrine'
            $readPlayerRepository: '@Infrastructure\Repository\Supabase\PlayerRepositorySupabase'
            $writePlayerRepository: '@Infrastructure\Repository\Doctrine\PlayerRepositoryDoctrine'
            $readMatchRepository: '@Infrastructure\Repository\Supabase\MatchRepositorySupabase'
            $writeMatchRepository: '@Infrastructure\Repository\Doctrine\MatchRepositoryDoctrine'
            $readParticipationRepository: '@Infrastructure\Repository\Supabase\ParticipationRepositorySupabase'
            $writeParticipationRepository: '@Infrastructure\Repository\Doctrine\ParticipationRepositoryDoctrine'
            $championshipMapper: '@Infrastructure\Entity\Doctrine\Mapper\ChampionshipMapperDoctrine'
            $teamMapper: '@Infrastructure\Entity\Doctrine\Mapper\TeamMapperDoctrine'
            $matchMapper: '@Infrastructure\Entity\Doctrine\Mapper\MatchMapperDoctrine'
            $participationMapper: '@Infrastructure\Entity\Doctrine\Mapper\ParticipationMapperDoctrine'

    Domain\UseCase\FetchPlayers\FetchPlayersUseCase:
        arguments:
            $playerRepository: '@Infrastructure\Repository\Doctrine\PlayerRepositoryDoctrine'

    Domain\UseCase\FetchMatchs\FetchMatchsUseCase:
        arguments:
            $matchRepository: '@Infrastructure\Repository\Doctrine\MatchRepositoryDoctrine'
            $matchMapper: '@Infrastructure\Entity\Doctrine\Mapper\MatchMapperDoctrine'

    Domain\UseCase\EditPlayer\EditPlayerUseCase:
        arguments:
            $playerRepository: '@Infrastructure\Repository\Doctrine\PlayerRepositoryDoctrine'
            $playerMapper: '@Infrastructure\Entity\Doctrine\Mapper\PlayerMapperDoctrine'

    Infrastructure\Repository\:
        resource: '../src/Infrastructure/Repository'
        autowire: true
        autoconfigure: true
        bind:
            string $apiUrl: '%env(SUPABASE_URL)%'
            string $apiKey: '%env(SUPABASE_API_KEY)%'

    Domain\Repository\ParticipationRepository: '@Infrastructure\Repository\Doctrine\ParticipationRepositoryDoctrine'
    Domain\Repository\PlacementRepository: '@Infrastructure\Repository\Doctrine\PlacementRepositoryDoctrine'
    Domain\Repository\PositionRepository: '@Infrastructure\Repository\Doctrine\PositionRepositoryDoctrine'
    Domain\Repository\PlayerRepository: '@Infrastructure\Repository\Doctrine\PlayerRepositoryDoctrine'
    Domain\Repository\TeamRepository: '@Infrastructure\Repository\Doctrine\TeamRepositoryDoctrine'
    Domain\Repository\ChampionshipRepository: '@Infrastructure\Repository\Doctrine\ChampionshipRepositoryDoctrine'
    Domain\Repository\MatchRepository: '@Infrastructure\Repository\Doctrine\MatchRepositoryDoctrine'
    Domain\UseCase\FetchPlayers\FetchPlayersOutputBoundary: '@Domain\Presenter\FetchPlayers\FetchPlayersPresenter'
    Domain\UseCase\ShowDetailsPlayer\ShowDetailsPlayerOutputBoundary: '@Domain\Presenter\ShowDetailsPlayer\ShowDetailsPlayerPresenter'
    Domain\UseCase\ShowDetailsMatch\ShowDetailsMatchOutputBoundary: '@Domain\Presenter\ShowDetailsMatch\ShowDetailsMatchPresenter'
    Domain\UseCase\FetchMatchs\FetchMatchsOutputBoundary: '@Domain\Presenter\FetchMatchs\FetchMatchsPresenter'
    Domain\Mapper\PlayerMapper: '@Infrastructure\Entity\Doctrine\Mapper\PlayerMapperDoctrine'
    Domain\Mapper\NoteMapper: '@Infrastructure\Entity\Doctrine\Mapper\NoteMapperDoctrine'
    Domain\Mapper\TeamMapper: '@Infrastructure\Entity\Doctrine\Mapper\TeamMapperDoctrine'
    Domain\Mapper\PositionMapper: '@Infrastructure\Entity\Doctrine\Mapper\PositionMapperDoctrine'
    Domain\Mapper\PlacementMapper: '@Infrastructure\Entity\Doctrine\Mapper\PlacementMapperDoctrine'
    Domain\Mapper\ChampionshipMapper: '@Infrastructure\Entity\Doctrine\Mapper\ChampionshipMapperDoctrine'


