# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Domain\:
        resource: '../src/Domain'
        exclude:
            - '../src/Domain/Entity'
            - '../src/Domain/ViewModel'

    Infrastructure\Symfony\Controller\:
        resource: '../src/Infrastructure/Symfony/Controller'
        tags: ['controller.service_arguments']

    Infrastructure\:
        resource: '../src/Infrastructure'
        exclude:
            - '../src/Infrastructure/Symfony/Controller'
            - '../src/Infrastructure/Twig'

    Domain\UseCase\FetchData\FetchDataUseCase:
        arguments:
            $readChampionshipRepository: '@Infrastructure\Repository\Supabase\ChampionshipRepositorySupabase'
            $writeChampionshipRepository: '@Infrastructure\Repository\Doctrine\ChampionshipRepositoryDoctrine'
            $readTeamRepository: '@Infrastructure\Repository\Supabase\TeamRepositorySupabase'
            $writeTeamRepository: '@Infrastructure\Repository\Doctrine\TeamRepositoryDoctrine'
            $readPlayerRepository: '@Infrastructure\Repository\Supabase\PlayerRepositorySupabase'
            $writePlayerRepository: '@Infrastructure\Repository\Doctrine\PlayerRepositoryDoctrine'

    Domain\UseCase\FetchPlayers\FetchPlayersUseCase:
        arguments:
            $playerRepository: '@Infrastructure\Repository\Doctrine\PlayerRepositoryDoctrine'

    Infrastructure\Repository\:
        resource: '../src/Infrastructure/Repository'
        autowire: true
        autoconfigure: true
        bind:
            string $apiUrl: '%env(SUPABASE_URL)%'
            string $apiKey: '%env(SUPABASE_API_KEY)%'

    Domain\Repository\PlayerRepository: '@Infrastructure\Repository\Supabase\PlayerRepositorySupabase'
    Domain\Repository\TeamRepository: '@Infrastructure\Repository\Supabase\TeamRepositorySupabase'
    Domain\Repository\ChampionshipRepository: '@Infrastructure\Repository\Supabase\ChampionshipRepositorySupabase'
    Domain\UseCase\FetchPlayers\FetchPlayersOutputBoundary: '@Domain\Presenter\FetchPlayers\FetchPlayersPresenter'
