# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Domain\:
        resource: '../src/Domain'
        exclude:
            - '../src/Domain/Entity'
            - '../src/Domain/ViewModel'

    Infrastructure\Symfony\Controller\:
        resource: '../src/Infrastructure/Symfony/Controller'
        tags: ['controller.service_arguments']

    Infrastructure\:
        resource: '../src/Infrastructure'
        exclude:
            - '../src/Infrastructure/Symfony/Controller'
            - '../src/Infrastructure/Twig'

    Infrastructure\Repository\:
        resource: '../src/Infrastructure/Repository'
        autowire: true
        autoconfigure: true
        bind:
            string $apiUrl: '%env(SUPABASE_URL)%'
            string $apiKey: '%env(SUPABASE_API_KEY)%'

    Domain\Repository\PlayerRepository: '@Infrastructure\Repository\Players\PlayerRepositorySupabase'
    Domain\Repository\TeamRepository: '@Infrastructure\Repository\Teams\TeamRepositorySupabase'
    Domain\UseCase\FetchPlayers\FetchPlayersOutputBoundary: '@Domain\Presenter\FetchPlayers\FetchPlayersPresenter'
